### ISSUE TITLE
Music Playback Lags Behind Drill Preview

### ISSUE THREAD

**Issue by quiescemusic** [OpenMarch/OpenMarch#208]
### Platform

I am using: 
BunsenLabs GNU/Linux 12 (Boron) x86_64
Kernel: 6.1.0-25-amd64 
npm: 9.2.0
node: 18.19.0

My computer is kind of old;
CPU: Intel i5-3470 (4) @ 3.600GHz
GPU: Intel HD Graphics

I am using the latest version of OpenMarch (I cloned the repository today).
### Description

The playback of an audio file lags behind the measures and counts of the drill preview (even when using the correct tempo or an imported XML file). Every measure, the drill preview gets a little bit more behind the music and it adds up quickly until the two are entirely separated.
I assume this is due to graphic rendering taking slightly more than the allotted measure time (but it may be due to my computer's old hardware).

Any ideas on the source of this problem or what a simple solution may be?

Thanks for everything you do! I am excited to see where this project goes.

**Comment by AlexDumo** [comment]
Thanks for the issue! The music synchronization implementation is kind of elementary. All it does is calculate timestamp given the tempo of the measures. 

I'd like two things:
1. Can you send the audio file and musicxml file you're using 
1. Did you generate the audio file directly from the notation software that made the musicXML? If so, can you check if there's any delay in the audio file itself? Some notation softwares will add a bit of padding at the start

There really needs to be a better synchronization system, but it really should be your slower computer that is the issue

**Comment by AlexDumo** [comment]
Just want to follow up @quiescemusic to make sure we can fix this. Could you provide the audio and musicXML files you're using?

**Comment by quiescemusic** [comment]
Ack I saw this and forgot to respond. I have been a tad bit busy recently and so I will try to find some time to work on this, but I should be able to get those files within the next few days. You can put the issue on low priority if that is best.

**Comment by quiescemusic** [comment]
Here are the MP3 and XML files I am using directly in OpenMarch. The
notation software used to generate & export such files is MuseScore
(v4.4.2).
It may be helpful to note the wording MuseScore's "About MusicXML" dialogue
box says, referring to this type of XML being used for sheet-music
exchange. Thus, it is possible that MuseScore is generating a brief pause
(or a slight latency between measures, line breaks, etc.) that causes the
aforementioned issue.

I wish you good favour in your endeavors to improve this wonderful
application and I will certainly be along for the ride!

**Comment by quiescemusic** [comment]
@AlexDumo 
I have discovered further evidence into the issue!
It appears that no matter what the tempo is changed to for a measure in OpenMarch, the program still executes it as the default (120 BPM). I don't know what the cause of this issue is, but I have tested this with and without XML and Audio files. The result is the same.

**Comment by AlexDumo** [comment]
This totally slipped my mind, apologies! I've been super busy working on curves and shapes.

This is a super glaring issue so this will be my next task today or tomorrow. Could you do me a favor and send me your '.dots' file? I think whatever music XML you used didn't parse correctly, so I need to make sure OpenMarch can handle it.

**Comment by quiescemusic** [comment]
I cannot find a '.dots' file anywhere on my computer. I'm rather confused about what that extension is.

Also, I tested the issue without an XML file and the results were the same. I tried setting the tempo in OpenMarch to something completely different like 20BPM and there was still no change in the simulation. 

However, here is a ZIP file containing the XML file, MP3 file and MSCZ file.

**Comment by AlexDumo** [comment]
The dots file is the file your OpenMarch show is saved in. If you forgot where it is, you can create a new one with the save button

**Comment by quiescemusic** [comment]
Its in here:
[ARKdots.zip](https://github.com/user-attachments/files/17987148/ARKdots.zip)

**Comment by AlexDumo** [comment]
Alright I have a couple band-aid that will help you and anyone else who encounters this issue. 

1. **Avoid accelerandos and decelerandos for now**
    - I acknowledge this is a pretty significant feature that's missing, but OpenMarch just can't handle gradual tempo changes yet
    - Remove them from your score and just put staff text denoting the tempo change (without actually changing the tempo)
    - You _may_ be able to manually input the tempo marking for each beat of the decel or accel (let me know if that works)
    - Make sure you recreate your audio file after doing this
1. **When creating a musicXML, only export a single part that has no notes on it**
    - You can create a dummy part at the bottom of the score and just delete it afterwards
    - Musescore lets you do this very easily
    - ![Screenshot 2024-12-03 at 7 39 47 AM](https://github.com/user-attachments/assets/4129f1c5-b240-45cd-bbed-1406f5fe9ac3)

I'm not marking this as closed yet because accels and deccels are fairly common and should be fixed. I think importing the barebones musicXML is just what people will have to do though. It doesn't seem like a huge deal to me and Musescore can easily accomplish that with musicXML from any software.

**Comment by quiescemusic** [comment]
Thanks for the help! I appreciate all you're doing to make this project a reality and I intend to continue following this journey.

**Comment by AlexDumo** [comment]
Gradual tempo bug moved to #237
